services:
  app:
    build: ./java_app
    extra_hosts: 
    - "host.docker.internal:host-gateway"
    ports:
    - "8080:8080"
  ldap:
    image: osixia/openldap:1.5.0
    ports:
    - "389:389"
    environment:
    - LDAP_ORGANISATION=Attacker
    - LDAP_DOMAIN=attacker.com
    - LDAP_ADMIN_PASSWORD=password